/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.pbo;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ASUS
 */
public class MenuCustomer extends javax.swing.JFrame {

    /**
     * Creates new form MenuCostumer
     */
    public MenuCustomer() {
        initComponents();
        loadCustomerData();
        loadSellerData();
        loadDriverData();
    }
    private void loadCustomerData() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Customer", "Nama"}, 0);
        try {
            Connection conn = dbConnection.getConnection();
            Statement stmt = conn.createStatement();
            String query = "SELECT id, nameFull FROM customer";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nameFull");
                model.addRow(new Object[]{id, nama});
            }

            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data customer: " + e.getMessage());
        }
    }

    private void loadSellerData() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Seller", "Nama"}, 0);
        try {
            Connection conn = dbConnection.getConnection();
            Statement stmt = conn.createStatement();
            String query = "SELECT id, nameFull FROM seller";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nameFull");
                model.addRow(new Object[]{id, nama});
            }

            jTable2.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data seller: " + e.getMessage());
        }
    }

    private void loadDriverData() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Driver", "Nama"}, 0);
        try {
            Connection conn = dbConnection.getConnection();
            Statement stmt = conn.createStatement();
            String query = "SELECT id, nameFull FROM driver";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nameFull");
                model.addRow(new Object[]{id, nama});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data driver: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitBT = new javax.swing.JButton();
        liatpesananBT = new javax.swing.JButton();
        buatpesananBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ketjumlahKaos = new javax.swing.JTextField();
        ketjumlahCelana = new javax.swing.JTextField();
        ketjumlahKemeja = new javax.swing.JTextField();
        pilihsellerTF = new javax.swing.JTextField();
        pilihdriverTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pbo/pp .png"))); // NOI18N
        jLabel1.setText("Costumer");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GO DRY");
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 55));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pbo/baju0.png"))); // NOI18N

        exitBT.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        exitBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pbo/exi.png"))); // NOI18N
        exitBT.setText("EXIT");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        liatpesananBT.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        liatpesananBT.setText("LIHAT STATUS PESANAN");
        liatpesananBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liatpesananBTActionPerformed(evt);
            }
        });

        buatpesananBT.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        buatpesananBT.setText("BUAT PESANAN");
        buatpesananBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatpesananBTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PILIH ID SELLER");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Seller ", "Nama"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(150, 400));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Seller ", "Nama"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(150, 400));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PILIH ID DRIVER");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of t-shirts (3000)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Number of shirts (4000)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Number of pants (5000)");

        ketjumlahKaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketjumlahKaosActionPerformed(evt);
            }
        });

        ketjumlahCelana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketjumlahCelanaActionPerformed(evt);
            }
        });

        ketjumlahKemeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketjumlahKemejaActionPerformed(evt);
            }
        });

        pilihsellerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihsellerTFActionPerformed(evt);
            }
        });

        pilihdriverTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihdriverTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(liatpesananBT)
                                .addGap(18, 18, 18)
                                .addComponent(buatpesananBT)
                                .addGap(18, 18, 18)
                                .addComponent(exitBT))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(29, 29, 29)
                                                .addComponent(ketjumlahKemeja))
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(29, 29, 29)
                                                .addComponent(ketjumlahCelana))
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(ketjumlahKaos)))
                                        .addGap(71, 71, 71))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(41, 41, 41)
                                        .addComponent(pilihdriverTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pilihsellerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGap(163, 359, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(ketjumlahKaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(ketjumlahKemeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(ketjumlahCelana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(pilihsellerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(pilihdriverTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liatpesananBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBT)
                    .addComponent(buatpesananBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liatpesananBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liatpesananBTActionPerformed
        // TODO add your handling code here:
        Pesanan pesananForm = new Pesanan();
        pesananForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_liatpesananBTActionPerformed

    private void buatpesananBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatpesananBTActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil data dari text field
            int jumlahKaos = Integer.parseInt(ketjumlahKaos.getText());
            int jumlahKemeja = Integer.parseInt(ketjumlahKemeja.getText());
            int jumlahCelana = Integer.parseInt(ketjumlahCelana.getText());
    
            String idSeller = pilihsellerTF.getText();
            String idDriver = pilihdriverTF.getText();

            // Validasi input
            if (jumlahKaos <= 0 || jumlahKemeja <= 0 || jumlahCelana <= 0 || idSeller.isEmpty() || idDriver.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pastikan semua data telah diisi dengan benar.", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Menghitung total biaya
            int totalCost = (jumlahKaos * 3000) + (jumlahKemeja * 4000) + (jumlahCelana * 5000);
    
            // Proses pembuatan pesanan
            Connection conn = dbConnection.getConnection();
            Statement stmt = conn.createStatement();
            String query = "INSERT INTO pesanan (idSeller, idDriver, totalTshirt, totalShirt, totalPants, totalCost, statusPesanan) "
                 + "VALUES ('" + idSeller + "', '" + idDriver + "', '" + "', " 
                 + jumlahKaos + ", " + jumlahKemeja + ", " + jumlahCelana + ", " + totalCost + ", 'Pending')";

            int result = stmt.executeUpdate(query);
    
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Pesanan berhasil dibuat!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuat pesanan.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }

            // Reset input form
            ketjumlahKaos.setText("");  
            ketjumlahKemeja.setText("");
            ketjumlahCelana.setText("");
            pilihsellerTF.setText("");
            pilihdriverTF.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap masukkan angka yang valid untuk jumlah pakaian.", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuat pesanan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buatpesananBTActionPerformed

    private void ketjumlahKaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketjumlahKaosActionPerformed
        // TODO add your handling code here:
        ketjumlahKaos.setText("");
    }//GEN-LAST:event_ketjumlahKaosActionPerformed

    private void ketjumlahKemejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketjumlahKemejaActionPerformed
        // TODO add your handling code here:
        ketjumlahKemeja.setText("");
    }//GEN-LAST:event_ketjumlahKemejaActionPerformed

    private void ketjumlahCelanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketjumlahCelanaActionPerformed
        // TODO add your handling code here:
        ketjumlahCelana.setText("");
    }//GEN-LAST:event_ketjumlahCelanaActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        new Terimakasih().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBTActionPerformed

    private void pilihsellerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihsellerTFActionPerformed
        // TODO add your handling code here:
        pilihsellerTF.setText("");
    }//GEN-LAST:event_pilihsellerTFActionPerformed

    private void pilihdriverTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihdriverTFActionPerformed
        // TODO add your handling code here:
        pilihdriverTF.setText("");
    }//GEN-LAST:event_pilihdriverTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton buatpesananBT;
    private javax.swing.JButton exitBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField ketjumlahCelana;
    private javax.swing.JTextField ketjumlahKaos;
    private javax.swing.JTextField ketjumlahKemeja;
    private javax.swing.JButton liatpesananBT;
    private javax.swing.JTextField pilihdriverTF;
    private javax.swing.JTextField pilihsellerTF;
    // End of variables declaration//GEN-END:variables
}
